### ISSUE TITLE
"No Tokens to Redeem" 

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions-app#109]
When a user has redeemable tokens but there are no assets in the vault the error displayed is that there are "no tokens to redeem"

<img width="444" alt="image" src="https://user-images.githubusercontent.com/4986634/67335026-19e14480-f4f1-11e9-9559-f0852374de71.png">

This is a bit confusing because the user has tokens to redeem... This dialogue should say something like "There are currently no assets in the vault".

**Comment by fabriziovigevani** [comment]
How about "No assets in the vault" ?

**Comment by lkngtn** [comment]
Maybe we should say “No eligible assets in the vault” as there may be assets just not any assets that have been added to the redemptions list?
