### ISSUE TITLE
Removing an asset requires a hover state

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions-app#114]
We should try and find a way to way to show this that doesn't suck but also doesn't break accessibility.

**Comment by fabriziovigevani** [comment]
Was struggling a little bit with Figma so i thought to just share here with a brief explanation.

Was thinking to change the button to be for adding and removing tokens, then in the side panel we would show the Add and remove tabs (like finance does for deposit and withdraw).

**The Add tab would be as it is. The remove Tab would display 
a selectable list of the redeemable tokens.**

![Screen Shot 2019-11-08 at 3 55 08 PM](https://user-images.githubusercontent.com/22663232/68502873-3fd04e00-0240-11ea-91de-85a981e8edad.png)

**Had other alternatives but realized they wouldn't go well in small screens:
This way i think it's the most straight forward and intuitive**

![Screen Shot 2019-11-08 at 4 00 39 PM](https://user-images.githubusercontent.com/22663232/68503163-fdf3d780-0240-11ea-8265-5ddce10cc1a7.png)
