### ISSUE TITLE
Forwarders and msg.sender interaction

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions-app#13]
My understanding from our conversation today is that right now the current implementation will only work if we allow ANY_ENTITY the ability to redeem, or we explicitly define addresses which can call the function. 

Assigning the role to a Token Manager to allow anyone with tokens to call the redeem function through forwarding will not work, because the redemptions-app will not be aware of the true message sender. 

Is this a correct interpretation? And is [this issue](https://github.com/aragon/aragon/issues/452) relevant?

**Comment by fabriziovigevani** [comment]
Yes, your interpretation is accurate.
I don’t really see the referenced issue being  relevant for our case as for what i understood it’s only for forwarding description.

Side note: Having the token manager as forwarder for redeem function and  passing the redeemer’s address as argument in the redeem function  would also not work or any redeemable token holder could force another holder to redeem his tokens.

Ill take a look at how params work on permissions and if it’s something we could use in this case as @willjgriff mentioned on another issue.

**Comment by lkngtn** [comment]
> Side note: Having the token manager as forwarder for redeem function and passing the redeemer’s address as argument in the redeem function would also not work or any redeemable token holder could force another holder to redeem his tokens.

Yeah it shouldn't be a user settable parameter, which means that we really need to the token manager to pass message sender as input when forwarding the action. I know there has been other conversations about the need for forwarders to pass contextual information (like in that issue), but I think that it applies to more than just descriptions. Being able to see the original msg.sender throughout the forwarding process seems like something that should be standardized in aragonOS.

**Comment by lkngtn** [comment]
From @willjgriff comment on the [other thread](https://github.com/1Hive/dissent-app/issues/1#issuecomment-493783049), but probably more relevant to discuss here...

> To support the Redemptions use case, this would require the Redemptions redeem permission only be given to an address that implements the dissent forwarder. I believe this would require modifying the current Redemptions app to not use msg.sender in the redeem function which means any DAO using the Redemptions app without the forwarder would have to set permissions with params (the param being what was msg.sender).

I'm not sure I follow how setting the permissions with parameters would work. What would be the parameter we would be setting and what permission would be granted?

**Comment by lkngtn** [comment]
After asking in #dev-help if there was a way to retrieve the original msg.sender when interacting with forwarders on rocket chat @sohkai suggested the following: 

> You can get it via `tx.origin`, but beware of its pitfalls with authentication (https://medium.com/coinmonks/solidity-tx-origin-attacks-58211ad95514)

**Comment by lkngtn** [comment]
I spoke with @izqui about this and he suggested that the best approach would be to have the original sender sign a message which can be passed in the intent (through forwarders like the token manager) and used by the redemptions app to securely identify the sender's address at the time the redemption happens. 

The redemptions app would need to recover the original senders address by validating the signature of a fixed data blob. The data blob can be hard coded in the redemptions app.
