### ISSUE TITLE
Design mock up

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions-app#2]
Should show user the current exchange rate between the token and vault assets. 

Should allow users to click a redeem tokens button, and then enter the amount of tokens they want to exchange and preview the assets they would recieve in exchange before confirming the transaction.

**Comment by 0xGabi** [comment]
We meet today with @fabriziovigevani and we got exited to work on a mock of the redemptions app. I know there is already plans to talk with Paty to have insight on how to represent the UI/UX, so if it is useful this is the idea we jam:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/9082013/57818900-62cfe880-775c-11e9-9d32-a06456175cbc.png">

**Comment by lkngtn** [comment]
😍😍😍

Love it!

**Comment by rperez89** [comment]
I imagine it with the Aragon UI 💯

**Comment by lkngtn** [comment]
I wonder if:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/4986634/57820056-1c2cbf00-7759-11e9-8444-df44f030f2bd.png">

should be shown only when you click a "redeem" button. So on the  top right you would have a "redeem" button, and perhaps have the add token next to the rest of the tokens in the list.

**Comment by 0xGabi** [comment]
You also meant as a popup panel? Or apear in the bottom of the UI?

**Comment by lkngtn** [comment]
> You also meant as a popup panel?

Yeah I mean in the transaction panel thing that typically pops up. So you would click redeem, then have the option to indicate how much you want to redeem and see a preview of what you would get in return.
