### ISSUE TITLE
Listen for Token Manager and Vault events

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/redemptions-app#27]
Currently the background script only listens for redemptions contract events. 

If new redeemable tokens are minted/burned, the RDT `total supply` should be refreshed (even current account's RDT balance in case it was the target address ).

Same thing happens with `vault` deposits/withdraws. 
If the deposit/withdraw token address is currently added in the redemption token list, it should refresh vault's token balance.

Currently you'll have to refresh redemptions app in order to see the changes.

**Comment by topocount** [comment]
Depending on how you want to accomplish this, it could be as simple as initializing the Redemptions app with the Vault and Token Manager app proxy addresses, and then using the addresses to set up a subscription in the script.js store. We haven't implemented this purely using the frontend, but it might be possible once aragon.js exposes all available DAO apps within each app context.

**Comment by fabriziovigevani** [comment]
Yes, actually we were thinking to do exactly that. We already initialize the app with the Token Manager and the Vault so adding to the array of events on api.store, the token manager and vault events would do.
Thinking that probably would be best to listen for events from current block? as we are only interested in those events rather than past ones.

**Comment by fabriziovigevani** [comment]
closed by #38
