### ISSUE TITLE
Upgrade app to use React hooks

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/redemptions-app#64]

**Comment by burrrata** [comment]
Is this for `redeemTokens.js`, `UpdateTokens.js`, and/or any other files?

Also, besides that hooks are awesome and componentDidMount sucks, is there any other reason to update to hooks?

**Comment by fabriziovigevani** [comment]
It's for any stateful component in our app. 

The main reason is because we plan to build the nexts apps with hooks so i think having them all built with the same API would be better. It's not an urgent issue though.
