### ISSUE TITLE
Frontend not loading after install

### ISSUE THREAD

**Issue by bingen** [1Hive/redemptions-app#66]
After installing Redemptions app on Rinkeby with the command show [here](https://1hive.org/projects/dandelion-orgs/redemptions-app): 
```
aragon dao install <dao-address> redemptions.open.aragonpm.eth --app-init-args <vault-address> <token-manager-address>
```

And creating one of its permissions (`ADD_TOKEN_ROLE`) with the following command:
```
aragon dao acl create --environment aragon:rinkeby 0x88D96395F381Cee3ed834A68880F68c93267f809 0x6E3C81907343335B71a95ae6198fa2d42E08C8CB ADD_TOKEN_ROLE 0x18D8D4fcC706DA09E8329d330059a0a8bE916c27 0x18D8D4fcC706DA09E8329d330059a0a8bE916c27
```

The app appears in Permissions and Settings but not in the Apps section. It seems that the frontend is not loaded. In Settings the app is marked as "CONTRACT-ONLY".
The only relevant message I see in the console is this one:
![Screenshot from 2019-07-24 11-10-40](https://user-images.githubusercontent.com/701095/61781919-7905bf00-ae05-11e9-81ae-0fc631fd9a04.png)

You can see the DAO here:

https://rinkeby.aragon.org/#/0x88D96395F381Cee3ed834A68880F68c93267f809

Am I missing any step?

Thanks.

**Comment by fabriziovigevani** [comment]
The `artifact.json` was published with an incorrect environment and appId. We made a minor upgrade that fixes this issue.

The problem i'm seeing now is that it's not automatically upgrading your installed instance (tried with my test DAO and happened the same). Seems like installing an app with some incorrect content, corrupts something in the DAO which i'm not sure how to fix. Checking in the app center, the apps won't load either. I will submit an issue on the Aragon client.

If you could try with a new dao in the meantime would be great. Alternatively you can try an already installed instance [here](https://rinkeby.aragon.org/#/tryredemptions/)

Thank you for your feedback.

**Comment by lkngtn** [comment]
@fabriziovigevani Please add a link to the issue in aragon aragon once you have created it. This feels like  an important issue to track.

**Comment by fabriziovigevani** [comment]
Issue: https://github.com/aragon/aragon/issues/892

**Comment by fabriziovigevani** [comment]
closed by https://github.com/aragon/aragon.js/pull/353

**Comment by fabriziovigevani** [comment]
closed by https://github.com/aragon/aragon.js/pull/353
