### ISSUE TITLE
Deploy new version of redemptions to rinkeby

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions-app#83]

**Comment by burrrata** [comment]
To confirm, we can redeploy the apps as many times as we want, but the installation command from the CLI will always point to `redemptions.open.aragonpm.eth` right?

**Comment by fabriziovigevani** [comment]
I'm not sure i understand what you mean.

You mean if the command will install the latest version published? Then yes.

**Comment by 0xGabi** [comment]
I have published a new major version.

Also I update the manager of the `Publish version` role on both `redemptions.open` and `redemptions-staging.open` repos.
