### ISSUE TITLE
Can't deploy redemptions on 0.8 Camino on Rinkeby

### ISSUE THREAD

**Issue by RuneOrion** [1Hive/redemptions-app#94]
I have tried deploying redemptions on Aragon 0.8 Camino with the Agent app. I also deployed 'Vault' as it was missing from the webapp rinkeby build. I used the Aragon-CLI to assist in getting this done.

I ensured that TRANSFER_ROLE permission on Vault and the BURN_ROLE permission on the Token Manager is done. 

My organisation contract on rinkeby is 0xEDEd31e0788C8D102dDd1850705654FDe82B17ac or https://rinkeby.aragon.org/#/v1adl/ that I am testing and playing around with.

I can add token id for redemption, I can remove token id for redemption. And my redemption is linked to my vault as it is reflected there. But I am getting this Error when I tried to 'Redeem' on the Redemptions app: 

> Action impossible
> The action failed to execute. You may not have the required permissions.

I followed the permissions and settings as in the webapp demo on https://rinkeby.aragon.org/#/tryredemptions. Is there some permissions that I'm neglicting.

**Comment by fabriziovigevani** [comment]
Hey!

I've noticed that our documentation is not up to date, sorry for that!
We have recently changed redemptions to work only by direct interaction instead of through forwarders. So the `REDEEM_ROLE` now should be granted to `Any account` instead of to the `Tokens` app.

In https://rinkeby.aragon.org/#/tryredemptions we don't have redemptions at the latest version so we will be upgrading there as well.

Thank you for trying it out!

**Comment by facerecog** [comment]
Great! I changed the `REDEEM_ROLE` to `Any Account` and that worked. Forgive on my naive question, but does this pose any risk that any account can redeem? or simply token holders?

**Comment by RuneOrion** [comment]
It's my pleasure to try it out. You folks are doing an excellent job and this is a much needed feature. Yes so I changed the `REDEEM_ROLE` to `Any Account` and that worked! Does this pose any risk or gaps that any account can redeem tokens, or only token holders?

**Comment by fabriziovigevani** [comment]
Thank you!

It does not pose any risk since we require when redeeming tokens that redeemer's balance is at least the amount is trying to redeem. 
Having the `tokens` app forwarding the action was just extra security.
